AWSTemplateFormatVersion: '2010-09-09'
Description: DEUNA - Online Payment Platform - Storage - 2024-02-09T19:03:07.908405+00:00
Outputs:
  ArtifactsBucketName:
    Description: Artifacts files bucket
    Export:
      Name: ArtifactsBucket
    Value: !Ref 'ArtifactExeBucket'
  ArtifactsBucketARNOutput:
    Description: S3 bucket for artifacts ARN
    Export:
      Name: ArtifactsBucketArn
    Value: !GetAtt 'ArtifactExeBucket.Arn'
Parameters:
  Environment:
    AllowedValues:
      - dev
      - qa
      - prod
    Description: Deployment environment
    Type: String
Resources:
  ArtifactExeBucket:
    Properties:
      BucketName: !Sub
        - ${BucketPrefix}-${BucketSuffix}
        - BucketPrefix: deuna-online-payment-platform-artifacts
          BucketSuffix: !Ref 'Environment'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    Type: AWS::S3::Bucket